part of 'fonts_service_test.dart';

const List<String> expectedAvailableFontsNames = [
  'ABeeZee',
  'Abel',
  'Abhaya Libre',
  'Abril Fatface',
  'Aclonica',
  'Acme',
  'Actor',
  'Adamina',
  'Advent Pro',
  'Aguafina Script',
  'Akaya Kanadaka',
  'Akaya Telivigala',
  'Akronim',
  'Akshar',
  'Aladin',
  'Alata',
  'Alatsi',
  'Aldrich',
  'Alef',
  'Alegreya',
  'Alegreya SC',
  'Alegreya Sans',
  'Alegreya Sans SC',
  'Aleo',
  'Alex Brush',
  'Alfa Slab One',
  'Alice',
  'Alike',
  'Alike Angular',
  'Allan',
  'Allerta',
  'Allerta Stencil',
  'Allison',
  'Allura',
  'Almarai',
  'Almendra',
  'Almendra Display',
  'Almendra SC',
  'Alumni Sans',
  'Alumni Sans Inline One',
  'Amarante',
  'Amaranth',
  'Amatic SC',
  'Amethysta',
  'Amiko',
  'Amiri',
  'Amita',
  'Anaheim',
  'Andada Pro',
  'Andika',
  'Andika New Basic',
  'Anek Bangla',
  'Anek Devanagari',
  'Anek Gujarati',
  'Anek Gurmukhi',
  'Anek Kannada',
  'Anek Latin',
  'Anek Malayalam',
  'Anek Odia',
  'Anek Tamil',
  'Anek Telugu',
  'Angkor',
  'Annie Use Your Telescope',
  'Anonymous Pro',
  'Antic',
  'Antic Didone',
  'Antic Slab',
  'Anton',
  'Antonio',
  'Anybody',
  'Arapey',
  'Arbutus',
  'Arbutus Slab',
  'Architects Daughter',
  'Archivo',
  'Archivo Black',
  'Archivo Narrow',
  'Are You Serious',
  'Aref Ruqaa',
  'Arima Madurai',
  'Arimo',
  'Arizonia',
  'Armata',
  'Arsenal',
  'Artifika',
  'Arvo',
  'Arya',
  'Asap',
  'Asap Condensed',
  'Asar',
  'Asset',
  'Assistant',
  'Astloch',
  'Asul',
  'Athiti',
  'Atkinson Hyperlegible',
  'Atma',
  'Atomic Age',
  'Aubrey',
  'Audiowide',
  'Autour One',
  'Average',
  'Average Sans',
  'Averia Gruesa Libre',
  'Averia Libre',
  'Averia Sans Libre',
  'Averia Serif Libre',
  'Azeret Mono',
  'B612',
  'B612 Mono',
  'BIZ UDGothic',
  'BIZ UDMincho',
  'BIZ UDPGothic',
  'BIZ UDPMincho',
  'Babylonica',
  'Bad Script',
  'Bahiana',
  'Bahianita',
  'Bai Jamjuree',
  'Bakbak One',
  'Ballet',
  'Baloo 2',
  'Baloo Bhai 2',
  'Baloo Bhaijaan 2',
  'Baloo Bhaina 2',
  'Baloo Chettan 2',
  'Baloo Da 2',
  'Baloo Paaji 2',
  'Baloo Tamma 2',
  'Baloo Tammudu 2',
  'Baloo Thambi 2',
  'Balsamiq Sans',
  'Balthazar',
  'Bangers',
  'Barlow',
  'Barlow Condensed',
  'Barlow Semi Condensed',
  'Barriecito',
  'Barrio',
  'Basic',
  'Baskervville',
  'Battambang',
  'Baumans',
  'Bayon',
  'Be Vietnam Pro',
  'Beau Rivage',
  'Bebas Neue',
  'Belgrano',
  'Bellefair',
  'Belleza',
  'Bellota',
  'Bellota Text',
  'BenchNine',
  'Benne',
  'Bentham',
  'Berkshire Swash',
  'Besley',
  'Beth Ellen',
  'Bevan',
  'BhuTuka Expanded One',
  'Big Shoulders Display',
  'Big Shoulders Inline Display',
  'Big Shoulders Inline Text',
  'Big Shoulders Stencil Display',
  'Big Shoulders Stencil Text',
  'Big Shoulders Text',
  'Bigelow Rules',
  'Bigshot One',
  'Bilbo',
  'Bilbo Swash Caps',
  'BioRhyme',
  'BioRhyme Expanded',
  'Birthstone',
  'Birthstone Bounce',
  'Biryani',
  'Bitter',
  'Black And White Picture',
  'Black Han Sans',
  'Black Ops One',
  'Blinker',
  'Bodoni Moda',
  'Bokor',
  'Bona Nova',
  'Bonbon',
  'Bonheur Royale',
  'Boogaloo',
  'Bowlby One',
  'Bowlby One SC',
  'Brawler',
  'Bree Serif',
  'Brygada 1918',
  'Bubblegum Sans',
  'Bubbler One',
  'Buda',
  'Buenard',
  'Bungee',
  'Bungee Hairline',
  'Bungee Inline',
  'Bungee Outline',
  'Bungee Shade',
  'Butcherman',
  'Butterfly Kids',
  'Cabin',
  'Cabin Condensed',
  'Cabin Sketch',
  'Caesar Dressing',
  'Cagliostro',
  'Cairo',
  'Caladea',
  'Calistoga',
  'Calligraffitti',
  'Cambay',
  'Cambo',
  'Candal',
  'Cantarell',
  'Cantata One',
  'Cantora One',
  'Capriola',
  'Caramel',
  'Carattere',
  'Cardo',
  'Carme',
  'Carrois Gothic',
  'Carrois Gothic SC',
  'Carter One',
  'Castoro',
  'Catamaran',
  'Caudex',
  'Caveat',
  'Caveat Brush',
  'Cedarville Cursive',
  'Ceviche One',
  'Chakra Petch',
  'Changa',
  'Changa One',
  'Chango',
  'Charm',
  'Charmonman',
  'Chathura',
  'Chau Philomene One',
  'Chela One',
  'Chelsea Market',
  'Chenla',
  'Cherish',
  'Cherry Cream Soda',
  'Cherry Swash',
  'Chewy',
  'Chicle',
  'Chilanka',
  'Chivo',
  'Chonburi',
  'Cinzel',
  'Cinzel Decorative',
  'Clicker Script',
  'Coda',
  'Coda Caption',
  'Codystar',
  'Coiny',
  'Combo',
  'Comfortaa',
  'Comforter',
  'Comforter Brush',
  'Comic Neue',
  'Coming Soon',
  'Commissioner',
  'Concert One',
  'Condiment',
  'Content',
  'Contrail One',
  'Convergence',
  'Cookie',
  'Copse',
  'Corben',
  'Corinthia',
  'Cormorant',
  'Cormorant Garamond',
  'Cormorant Infant',
  'Cormorant SC',
  'Cormorant Unicase',
  'Cormorant Upright',
  'Courgette',
  'Courier Prime',
  'Cousine',
  'Coustard',
  'Covered By Your Grace',
  'Crafty Girls',
  'Creepster',
  'Crete Round',
  'Crimson Pro',
  'Croissant One',
  'Crushed',
  'Cuprum',
  'Cute Font',
  'Cutive',
  'Cutive Mono',
  'DM Mono',
  'DM Sans',
  'DM Serif Display',
  'DM Serif Text',
  'Damion',
  'Dancing Script',
  'Dangrek',
  'Darker Grotesque',
  'David Libre',
  'Dawning of a New Day',
  'Days One',
  'Dekko',
  'Dela Gothic One',
  'Delius',
  'Delius Swash Caps',
  'Delius Unicase',
  'Della Respira',
  'Denk One',
  'Devonshire',
  'Dhurjati',
  'Didact Gothic',
  'Diplomata',
  'Diplomata SC',
  'Do Hyeon',
  'Dokdo',
  'Domine',
  'Donegal One',
  'Dongle',
  'Doppio One',
  'Dorsa',
  'Dosis',
  'DotGothic16',
  'Dr Sugiyama',
  'Duru Sans',
  'Dynalight',
  'EB Garamond',
  'Eagle Lake',
  'East Sea Dokdo',
  'Eater',
  'Economica',
  'Eczar',
  'El Messiri',
  'Electrolize',
  'Elsie',
  'Elsie Swash Caps',
  'Emblema One',
  'Emilys Candy',
  'Encode Sans',
  'Encode Sans Condensed',
  'Encode Sans Expanded',
  'Encode Sans SC',
  'Encode Sans Semi Condensed',
  'Encode Sans Semi Expanded',
  'Engagement',
  'Englebert',
  'Enriqueta',
  'Ephesis',
  'Epilogue',
  'Erica One',
  'Esteban',
  'Estonia',
  'Euphoria Script',
  'Ewert',
  'Exo',
  'Exo 2',
  'Expletus Sans',
  'Explora',
  'Fahkwang',
  'Familjen Grotesk',
  'Fanwood Text',
  'Farro',
  'Farsan',
  'Fascinate',
  'Fascinate Inline',
  'Faster One',
  'Fasthand',
  'Fauna One',
  'Faustina',
  'Federant',
  'Federo',
  'Felipa',
  'Fenix',
  'Festive',
  'Finger Paint',
  'Fira Code',
  'Fira Mono',
  'Fira Sans',
  'Fira Sans Condensed',
  'Fira Sans Extra Condensed',
  'Fjalla One',
  'Fjord One',
  'Flamenco',
  'Flavors',
  'Fleur De Leah',
  'Flow Block',
  'Flow Circular',
  'Flow Rounded',
  'Fondamento',
  'Fontdiner Swanky',
  'Forum',
  'Francois One',
  'Frank Ruhl Libre',
  'Fraunces',
  'Freckle Face',
  'Fredericka the Great',
  'Fredoka',
  'Fredoka One',
  'Freehand',
  'Fresca',
  'Frijole',
  'Fruktur',
  'Fugaz One',
  'Fuggles',
  'Fuzzy Bubbles',
  'GFS Didot',
  'GFS Neohellenic',
  'Gabriela',
  'Gaegu',
  'Gafata',
  'Galada',
  'Galdeano',
  'Galindo',
  'Gamja Flower',
  'Gayathri',
  'Gelasio',
  'Gemunu Libre',
  'Genos',
  'Gentium Basic',
  'Gentium Book Basic',
  'Geo',
  'Georama',
  'Geostar',
  'Geostar Fill',
  'Germania One',
  'Gideon Roman',
  'Gidugu',
  'Gilda Display',
  'Girassol',
  'Give You Glory',
  'Glass Antiqua',
  'Glegoo',
  'Gloria Hallelujah',
  'Glory',
  'Gluten',
  'Goblin One',
  'Gochi Hand',
  'Goldman',
  'Gorditas',
  'Gothic A1',
  'Gotu',
  'Goudy Bookletter 1911',
  'Gowun Batang',
  'Gowun Dodum',
  'Graduate',
  'Grand Hotel',
  'Grandstander',
  'Grape Nuts',
  'Gravitas One',
  'Great Vibes',
  'Grechen Fuemen',
  'Grenze',
  'Grenze Gotisch',
  'Grey Qo',
  'Griffy',
  'Gruppo',
  'Gudea',
  'Gugi',
  'Gupter',
  'Gurajada',
  'Gwendolyn',
  'Habibi',
  'Hachi Maru Pop',
  'Hahmlet',
  'Halant',
  'Hammersmith One',
  'Hanalei',
  'Hanalei Fill',
  'Handlee',
  'Hanuman',
  'Happy Monkey',
  'Harmattan',
  'Headland One',
  'Heebo',
  'Henny Penny',
  'Hepta Slab',
  'Herr Von Muellerhoff',
  'Hi Melody',
  'Hina Mincho',
  'Hind',
  'Hind Guntur',
  'Hind Madurai',
  'Hind Siliguri',
  'Hind Vadodara',
  'Holtwood One SC',
  'Homemade Apple',
  'Homenaje',
  'Hubballi',
  'Hurricane',
  'IBM Plex Mono',
  'IBM Plex Sans',
  'IBM Plex Sans Arabic',
  'IBM Plex Sans Condensed',
  'IBM Plex Sans Devanagari',
  'IBM Plex Sans Hebrew',
  'IBM Plex Sans KR',
  'IBM Plex Sans Thai',
  'IBM Plex Sans Thai Looped',
  'IBM Plex Serif',
  'IM Fell DW Pica',
  'IM Fell DW Pica SC',
  'IM Fell Double Pica',
  'IM Fell Double Pica SC',
  'IM Fell English',
  'IM Fell English SC',
  'IM Fell French Canon',
  'IM Fell French Canon SC',
  'IM Fell Great Primer',
  'IM Fell Great Primer SC',
  'Ibarra Real Nova',
  'Iceberg',
  'Iceland',
  'Imbue',
  'Imperial Script',
  'Imprima',
  'Inconsolata',
  'Inder',
  'Indie Flower',
  'Ingrid Darling',
  'Inika',
  'Inknut Antiqua',
  'Inria Sans',
  'Inria Serif',
  'Inspiration',
  'Inter',
  'Irish Grover',
  'Island Moments',
  'Istok Web',
  'Italiana',
  'Italianno',
  'Itim',
  'Jacques Francois',
  'Jacques Francois Shadow',
  'Jaldi',
  'JetBrains Mono',
  'Jim Nightshade',
  'Jockey One',
  'Jolly Lodger',
  'Jomhuria',
  'Jomolhari',
  'Josefin Sans',
  'Josefin Slab',
  'Jost',
  'Joti One',
  'Jua',
  'Judson',
  'Julee',
  'Julius Sans One',
  'Junge',
  'Jura',
  'Just Another Hand',
  'Just Me Again Down Here',
  'K2D',
  'Kadwa',
  'Kaisei Decol',
  'Kaisei HarunoUmi',
  'Kaisei Opti',
  'Kaisei Tokumin',
  'Kalam',
  'Kameron',
  'Kanit',
  'Kantumruy',
  'Karantina',
  'Karla',
  'Karma',
  'Katibeh',
  'Kaushan Script',
  'Kavivanar',
  'Kavoon',
  'Kdam Thmor',
  'Keania One',
  'Kelly Slab',
  'Kenia',
  'Khand',
  'Khmer',
  'Khula',
  'Kings',
  'Kirang Haerang',
  'Kite One',
  'Kiwi Maru',
  'Klee One',
  'Knewave',
  'KoHo',
  'Kodchasan',
  'Koh Santepheap',
  'Kolker Brush',
  'Kosugi',
  'Kosugi Maru',
  'Kotta One',
  'Koulen',
  'Kranky',
  'Kreon',
  'Kristi',
  'Krona One',
  'Krub',
  'Kufam',
  'Kulim Park',
  'Kumar One',
  'Kumar One Outline',
  'Kumbh Sans',
  'Kurale',
  'La Belle Aurore',
  'Lacquer',
  'Laila',
  'Lakki Reddy',
  'Lalezar',
  'Lancelot',
  'Langar',
  'Lateef',
  'Lato',
  'Lavishly Yours',
  'League Gothic',
  'League Script',
  'League Spartan',
  'Leckerli One',
  'Ledger',
  'Lekton',
  'Lemon',
  'Lemonada',
  'Lexend',
  'Lexend Deca',
  'Lexend Exa',
  'Lexend Giga',
  'Lexend Mega',
  'Lexend Peta',
  'Lexend Tera',
  'Lexend Zetta',
  'Libre Barcode 128',
  'Libre Barcode 128 Text',
  'Libre Barcode 39',
  'Libre Barcode 39 Extended',
  'Libre Barcode 39 Extended Text',
  'Libre Barcode 39 Text',
  'Libre Barcode EAN13 Text',
  'Libre Baskerville',
  'Libre Bodoni',
  'Libre Caslon Display',
  'Libre Caslon Text',
  'Libre Franklin',
  'Licorice',
  'Life Savers',
  'Lilita One',
  'Lily Script One',
  'Limelight',
  'Linden Hill',
  'Literata',
  'Liu Jian Mao Cao',
  'Livvic',
  'Lobster',
  'Lobster Two',
  'Londrina Outline',
  'Londrina Shadow',
  'Londrina Sketch',
  'Londrina Solid',
  'Long Cang',
  'Lora',
  'Love Light',
  'Love Ya Like A Sister',
  'Loved by the King',
  'Lovers Quarrel',
  'Luckiest Guy',
  'Lusitana',
  'Lustria',
  'Luxurious Roman',
  'Luxurious Script',
  'M PLUS 1',
  'M PLUS 1 Code',
  'M PLUS 1p',
  'M PLUS 2',
  'M PLUS Code Latin',
  'M PLUS Rounded 1c',
  'Ma Shan Zheng',
  'Macondo',
  'Macondo Swash Caps',
  'Mada',
  'Magra',
  'Maiden Orange',
  'Maitree',
  'Major Mono Display',
  'Mako',
  'Mali',
  'Mallanna',
  'Mandali',
  'Manjari',
  'Manrope',
  'Mansalva',
  'Manuale',
  'Marcellus',
  'Marcellus SC',
  'Marck Script',
  'Margarine',
  'Markazi Text',
  'Marko One',
  'Marmelad',
  'Martel',
  'Martel Sans',
  'Marvel',
  'Mate',
  'Mate SC',
  'Maven Pro',
  'McLaren',
  'Mea Culpa',
  'Meddon',
  'MedievalSharp',
  'Medula One',
  'Meera Inimai',
  'Megrim',
  'Meie Script',
  'Meow Script',
  'Merienda',
  'Merienda One',
  'Merriweather',
  'Merriweather Sans',
  'Metal',
  'Metal Mania',
  'Metamorphous',
  'Metrophobic',
  'Michroma',
  'Milonga',
  'Miltonian',
  'Miltonian Tattoo',
  'Mina',
  'Miniver',
  'Miriam Libre',
  'Mirza',
  'Miss Fajardose',
  'Mitr',
  'Mochiy Pop One',
  'Mochiy Pop P One',
  'Modak',
  'Modern Antiqua',
  'Mogra',
  'Mohave',
  'Molengo',
  'Molle',
  'Monda',
  'Monofett',
  'Monoton',
  'Monsieur La Doulaise',
  'Montaga',
  'Montagu Slab',
  'MonteCarlo',
  'Montez',
  'Montserrat',
  'Montserrat Alternates',
  'Montserrat Subrayada',
  'Moo Lah Lah',
  'Moon Dance',
  'Moul',
  'Moulpali',
  'Mountains of Christmas',
  'Mouse Memoirs',
  'Mr Bedfort',
  'Mr Dafoe',
  'Mr De Haviland',
  'Mrs Saint Delafield',
  'Mrs Sheppards',
  'Ms Madi',
  'Mukta',
  'Mukta Mahee',
  'Mukta Malar',
  'Mukta Vaani',
  'Mulish',
  'Murecho',
  'MuseoModerno',
  'My Soul',
  'Mystery Quest',
  'NTR',
  'Nanum Brush Script',
  'Nanum Gothic',
  'Nanum Gothic Coding',
  'Nanum Myeongjo',
  'Nanum Pen Script',
  'Neonderthaw',
  'Nerko One',
  'Neucha',
  'Neuton',
  'New Rocker',
  'New Tegomin',
  'News Cycle',
  'Newsreader',
  'Niconne',
  'Niramit',
  'Nixie One',
  'Nobile',
  'Nokora',
  'Norican',
  'Nosifer',
  'Notable',
  'Nothing You Could Do',
  'Noticia Text',
  'Noto Emoji',
  'Noto Kufi Arabic',
  'Noto Music',
  'Noto Naskh Arabic',
  'Noto Nastaliq Urdu',
  'Noto Rashi Hebrew',
  'Noto Sans',
  'Noto Sans Adlam',
  'Noto Sans Adlam Unjoined',
  'Noto Sans Anatolian Hieroglyphs',
  'Noto Sans Arabic',
  'Noto Sans Armenian',
  'Noto Sans Avestan',
  'Noto Sans Balinese',
  'Noto Sans Bamum',
  'Noto Sans Bassa Vah',
  'Noto Sans Batak',
  'Noto Sans Bengali',
  'Noto Sans Bhaiksuki',
  'Noto Sans Brahmi',
  'Noto Sans Buginese',
  'Noto Sans Buhid',
  'Noto Sans Canadian Aboriginal',
  'Noto Sans Carian',
  'Noto Sans Caucasian Albanian',
  'Noto Sans Chakma',
  'Noto Sans Cham',
  'Noto Sans Cherokee',
  'Noto Sans Coptic',
  'Noto Sans Cuneiform',
  'Noto Sans Cypriot',
  'Noto Sans Deseret',
  'Noto Sans Devanagari',
  'Noto Sans Display',
  'Noto Sans Duployan',
  'Noto Sans Egyptian Hieroglyphs',
  'Noto Sans Elbasan',
  'Noto Sans Elymaic',
  'Noto Sans Georgian',
  'Noto Sans Glagolitic',
  'Noto Sans Gothic',
  'Noto Sans Grantha',
  'Noto Sans Gujarati',
  'Noto Sans Gunjala Gondi',
  'Noto Sans Gurmukhi',
  'Noto Sans Hanifi Rohingya',
  'Noto Sans Hanunoo',
  'Noto Sans Hatran',
  'Noto Sans Hebrew',
  'Noto Sans Imperial Aramaic',
  'Noto Sans Indic Siyaq Numbers',
  'Noto Sans Inscriptional Pahlavi',
  'Noto Sans Inscriptional Parthian',
  'Noto Sans Javanese',
  'Noto Sans Kaithi',
  'Noto Sans Kannada',
  'Noto Sans Kayah Li',
  'Noto Sans Kharoshthi',
  'Noto Sans Khmer',
  'Noto Sans Khojki',
  'Noto Sans Khudawadi',
  'Noto Sans Lao',
  'Noto Sans Lepcha',
  'Noto Sans Limbu',
  'Noto Sans Linear A',
  'Noto Sans Linear B',
  'Noto Sans Lisu',
  'Noto Sans Lycian',
  'Noto Sans Lydian',
  'Noto Sans Mahajani',
  'Noto Sans Malayalam',
  'Noto Sans Mandaic',
  'Noto Sans Manichaean',
  'Noto Sans Marchen',
  'Noto Sans Masaram Gondi',
  'Noto Sans Math',
  'Noto Sans Mayan Numerals',
  'Noto Sans Medefaidrin',
  'Noto Sans Meetei Mayek',
  'Noto Sans Meroitic',
  'Noto Sans Miao',
  'Noto Sans Modi',
  'Noto Sans Mongolian',
  'Noto Sans Mono',
  'Noto Sans Mro',
  'Noto Sans Multani',
  'Noto Sans Myanmar',
  'Noto Sans N Ko',
  'Noto Sans Nabataean',
  'Noto Sans New Tai Lue',
  'Noto Sans Newa',
  'Noto Sans Nushu',
  'Noto Sans Ogham',
  'Noto Sans Ol Chiki',
  'Noto Sans Old Hungarian',
  'Noto Sans Old Italic',
  'Noto Sans Old North Arabian',
  'Noto Sans Old Permic',
  'Noto Sans Old Persian',
  'Noto Sans Old Sogdian',
  'Noto Sans Old South Arabian',
  'Noto Sans Old Turkic',
  'Noto Sans Oriya',
  'Noto Sans Osage',
  'Noto Sans Osmanya',
  'Noto Sans Pahawh Hmong',
  'Noto Sans Palmyrene',
  'Noto Sans Pau Cin Hau',
  'Noto Sans Phags Pa',
  'Noto Sans Phoenician',
  'Noto Sans Psalter Pahlavi',
  'Noto Sans Rejang',
  'Noto Sans Runic',
  'Noto Sans Samaritan',
  'Noto Sans Saurashtra',
  'Noto Sans Sharada',
  'Noto Sans Shavian',
  'Noto Sans Siddham',
  'Noto Sans Sinhala',
  'Noto Sans Sogdian',
  'Noto Sans Sora Sompeng',
  'Noto Sans Soyombo',
  'Noto Sans Sundanese',
  'Noto Sans Syloti Nagri',
  'Noto Sans Symbols',
  'Noto Sans Symbols 2',
  'Noto Sans Syriac',
  'Noto Sans Tagalog',
  'Noto Sans Tagbanwa',
  'Noto Sans Tai Le',
  'Noto Sans Tai Tham',
  'Noto Sans Tai Viet',
  'Noto Sans Takri',
  'Noto Sans Tamil',
  'Noto Sans Tamil Supplement',
  'Noto Sans Telugu',
  'Noto Sans Thaana',
  'Noto Sans Thai',
  'Noto Sans Thai Looped',
  'Noto Sans Tifinagh',
  'Noto Sans Tirhuta',
  'Noto Sans Ugaritic',
  'Noto Sans Vai',
  'Noto Sans Wancho',
  'Noto Sans Warang Citi',
  'Noto Sans Yi',
  'Noto Sans Zanabazar Square',
  'Noto Serif',
  'Noto Serif Ahom',
  'Noto Serif Armenian',
  'Noto Serif Balinese',
  'Noto Serif Bengali',
  'Noto Serif Devanagari',
  'Noto Serif Display',
  'Noto Serif Dogra',
  'Noto Serif Ethiopic',
  'Noto Serif Georgian',
  'Noto Serif Grantha',
  'Noto Serif Gujarati',
  'Noto Serif Gurmukhi',
  'Noto Serif Hebrew',
  'Noto Serif Kannada',
  'Noto Serif Khmer',
  'Noto Serif Lao',
  'Noto Serif Malayalam',
  'Noto Serif Myanmar',
  'Noto Serif Nyiakeng Puachue Hmong',
  'Noto Serif Sinhala',
  'Noto Serif Tamil',
  'Noto Serif Tangut',
  'Noto Serif Telugu',
  'Noto Serif Thai',
  'Noto Serif Tibetan',
  'Noto Serif Yezidi',
  'Noto Traditional Nushu',
  'Nova Cut',
  'Nova Flat',
  'Nova Mono',
  'Nova Oval',
  'Nova Round',
  'Nova Script',
  'Nova Slim',
  'Nova Square',
  'Numans',
  'Nunito',
  'Nunito Sans',
  'Odibee Sans',
  'Odor Mean Chey',
  'Offside',
  'Oi',
  'Old Standard TT',
  'Oldenburg',
  'Ole',
  'Oleo Script',
  'Oleo Script Swash Caps',
  'Oooh Baby',
  'Open Sans',
  'Open Sans Condensed',
  'Oranienbaum',
  'Orbitron',
  'Oregano',
  'Orelega One',
  'Orienta',
  'Original Surfer',
  'Oswald',
  'Otomanopee One',
  'Outfit',
  'Over the Rainbow',
  'Overlock',
  'Overlock SC',
  'Overpass',
  'Overpass Mono',
  'Ovo',
  'Oxanium',
  'Oxygen',
  'Oxygen Mono',
  'PT Mono',
  'PT Sans',
  'PT Sans Caption',
  'PT Sans Narrow',
  'PT Serif',
  'PT Serif Caption',
  'Pacifico',
  'Padauk',
  'Palanquin',
  'Palanquin Dark',
  'Palette Mosaic',
  'Pangolin',
  'Paprika',
  'Parisienne',
  'Passero One',
  'Passion One',
  'Passions Conflict',
  'Pathway Gothic One',
  'Patrick Hand',
  'Patrick Hand SC',
  'Pattaya',
  'Patua One',
  'Pavanam',
  'Paytone One',
  'Peddana',
  'Peralta',
  'Permanent Marker',
  'Petemoss',
  'Petit Formal Script',
  'Petrona',
  'Philosopher',
  'Piazzolla',
  'Piedra',
  'Pinyon Script',
  'Pirata One',
  'Plaster',
  'Play',
  'Playball',
  'Playfair Display',
  'Playfair Display SC',
  'Plus Jakarta Sans',
  'Podkova',
  'Poiret One',
  'Poller One',
  'Poly',
  'Pompiere',
  'Pontano Sans',
  'Poor Story',
  'Poppins',
  'Port Lligat Sans',
  'Port Lligat Slab',
  'Potta One',
  'Pragati Narrow',
  'Praise',
  'Prata',
  'Preahvihear',
  'Press Start 2P',
  'Pridi',
  'Princess Sofia',
  'Prociono',
  'Prompt',
  'Prosto One',
  'Proza Libre',
  'Public Sans',
  'Puppies Play',
  'Puritan',
  'Purple Purse',
  'Qahiri',
  'Quando',
  'Quantico',
  'Quattrocento',
  'Quattrocento Sans',
  'Questrial',
  'Quicksand',
  'Quintessential',
  'Qwigley',
  'Qwitcher Grypen',
  'Racing Sans One',
  'Radio Canada',
  'Radley',
  'Rajdhani',
  'Rakkas',
  'Raleway',
  'Raleway Dots',
  'Ramabhadra',
  'Ramaraja',
  'Rambla',
  'Rammetto One',
  'Rampart One',
  'Ranchers',
  'Rancho',
  'Ranga',
  'Rasa',
  'Rationale',
  'Ravi Prakash',
  'Readex Pro',
  'Recursive',
  'Red Hat Display',
  'Red Hat Mono',
  'Red Hat Text',
  'Red Rose',
  'Redacted',
  'Redacted Script',
  'Redressed',
  'Reem Kufi',
  'Reenie Beanie',
  'Reggae One',
  'Revalia',
  'Rhodium Libre',
  'Ribeye',
  'Ribeye Marrow',
  'Righteous',
  'Risque',
  'Road Rage',
  'Roboto',
  'Roboto Condensed',
  'Roboto Flex',
  'Roboto Mono',
  'Roboto Serif',
  'Roboto Slab',
  'Rochester',
  'Rock 3D',
  'Rock Salt',
  'RocknRoll One',
  'Rokkitt',
  'Romanesco',
  'Ropa Sans',
  'Rosario',
  'Rosarivo',
  'Rouge Script',
  'Rowdies',
  'Rozha One',
  'Rubik',
  'Rubik Beastly',
  'Rubik Bubbles',
  'Rubik Glitch',
  'Rubik Microbe',
  'Rubik Mono One',
  'Rubik Moonrocks',
  'Rubik Puddles',
  'Rubik Wet Paint',
  'Ruda',
  'Rufina',
  'Ruge Boogie',
  'Ruluko',
  'Rum Raisin',
  'Ruslan Display',
  'Russo One',
  'Ruthie',
  'Rye',
  'STIX Two Text',
  'Sacramento',
  'Sahitya',
  'Sail',
  'Saira',
  'Saira Condensed',
  'Saira Extra Condensed',
  'Saira Semi Condensed',
  'Saira Stencil One',
  'Salsa',
  'Sanchez',
  'Sancreek',
  'Sansita',
  'Sansita Swashed',
  'Sarabun',
  'Sarala',
  'Sarina',
  'Sarpanch',
  'Sassy Frass',
  'Satisfy',
  'Sawarabi Gothic',
  'Sawarabi Mincho',
  'Scada',
  'Scheherazade New',
  'Schoolbell',
  'Scope One',
  'Seaweed Script',
  'Secular One',
  'Sedgwick Ave',
  'Sedgwick Ave Display',
  'Sen',
  'Send Flowers',
  'Sevillana',
  'Seymour One',
  'Shadows Into Light',
  'Shadows Into Light Two',
  'Shalimar',
  'Shanti',
  'Share',
  'Share Tech',
  'Share Tech Mono',
  'Shippori Antique',
  'Shippori Antique B1',
  'Shippori Mincho',
  'Shippori Mincho B1',
  'Shizuru',
  'Shojumaru',
  'Short Stack',
  'Shrikhand',
  'Siemreap',
  'Sigmar One',
  'Signika',
  'Signika Negative',
  'Simonetta',
  'Single Day',
  'Sintony',
  'Sirin Stencil',
  'Six Caps',
  'Skranji',
  'Slabo 13px',
  'Slabo 27px',
  'Slackey',
  'Smokum',
  'Smooch',
  'Smooch Sans',
  'Smythe',
  'Sniglet',
  'Snippet',
  'Snowburst One',
  'Sofadi One',
  'Sofia',
  'Solway',
  'Song Myung',
  'Sonsie One',
  'Sora',
  'Sorts Mill Goudy',
  'Source Code Pro',
  'Source Sans 3',
  'Source Sans Pro',
  'Source Serif 4',
  'Source Serif Pro',
  'Space Grotesk',
  'Space Mono',
  'Special Elite',
  'Spectral',
  'Spectral SC',
  'Spicy Rice',
  'Spinnaker',
  'Spirax',
  'Spline Sans',
  'Squada One',
  'Square Peg',
  'Sree Krushnadevaraya',
  'Sriracha',
  'Srisakdi',
  'Staatliches',
  'Stalemate',
  'Stalinist One',
  'Stardos Stencil',
  'Stick',
  'Stick No Bills',
  'Stint Ultra Condensed',
  'Stint Ultra Expanded',
  'Stoke',
  'Strait',
  'Style Script',
  'Stylish',
  'Sue Ellen Francisco',
  'Suez One',
  'Sulphur Point',
  'Sumana',
  'Sunflower',
  'Sunshiney',
  'Supermercado One',
  'Sura',
  'Suranna',
  'Suravaram',
  'Suwannaphum',
  'Swanky and Moo Moo',
  'Syncopate',
  'Syne',
  'Syne Mono',
  'Syne Tactile',
  'Tajawal',
  'Tangerine',
  'Tapestry',
  'Taprom',
  'Tauri',
  'Taviraj',
  'Teko',
  'Telex',
  'Tenali Ramakrishna',
  'Tenor Sans',
  'Text Me One',
  'Texturina',
  'Thasadith',
  'The Girl Next Door',
  'The Nautigal',
  'Tienne',
  'Tillana',
  'Timmana',
  'Tinos',
  'Titan One',
  'Titillium Web',
  'Tomorrow',
  'Tourney',
  'Trade Winds',
  'Train One',
  'Trirong',
  'Trispace',
  'Trocchi',
  'Trochut',
  'Truculenta',
  'Trykker',
  'Tulpen One',
  'Turret Road',
  'Twinkle Star',
  'Ubuntu',
  'Ubuntu Condensed',
  'Ubuntu Mono',
  'Uchen',
  'Ultra',
  'Uncial Antiqua',
  'Underdog',
  'Unica One',
  'UnifrakturCook',
  'UnifrakturMaguntia',
  'Unkempt',
  'Unlock',
  'Unna',
  'Updock',
  'Urbanist',
  'VT323',
  'Vampiro One',
  'Varela',
  'Varela Round',
  'Varta',
  'Vast Shadow',
  'Vazirmatn',
  'Vesper Libre',
  'Viaoda Libre',
  'Vibes',
  'Vibur',
  'Vidaloka',
  'Viga',
  'Voces',
  'Volkhov',
  'Vollkorn',
  'Vollkorn SC',
  'Voltaire',
  'Vujahday Script',
  'Waiting for the Sunrise',
  'Wallpoet',
  'Walter Turncoat',
  'Warnes',
  'Water Brush',
  'Waterfall',
  'Wellfleet',
  'Wendy One',
  'Whisper',
  'WindSong',
  'Wire One',
  'Work Sans',
  'Xanh Mono',
  'Yaldevi',
  'Yanone Kaffeesatz',
  'Yantramanav',
  'Yatra One',
  'Yellowtail',
  'Yeon Sung',
  'Yeseva One',
  'Yesteryear',
  'Yomogi',
  'Yrsa',
  'Yuji Boku',
  'Yuji Hentaigana Akari',
  'Yuji Hentaigana Akebono',
  'Yuji Mai',
  'Yuji Syuku',
  'Yusei Magic',
  'ZCOOL KuaiLe',
  'ZCOOL QingKe HuangYou',
  'ZCOOL XiaoWei',
  'Zen Antique',
  'Zen Antique Soft',
  'Zen Dots',
  'Zen Kaku Gothic Antique',
  'Zen Kaku Gothic New',
  'Zen Kurenaido',
  'Zen Loop',
  'Zen Maru Gothic',
  'Zen Old Mincho',
  'Zen Tokyo Zoo',
  'Zeyada',
  'Zhi Mang Xing',
  'Zilla Slab',
  'Zilla Slab Highlight',
];

const List<String> expectedFontFamilyNames = [
  'ABeeZee_regular',
  'Abel_regular',
  'AbhayaLibre_regular',
  'AbrilFatface_regular',
  'Aclonica_regular',
  'Acme_regular',
  'Actor_regular',
  'Adamina_regular',
  'AdventPro_regular',
  'AguafinaScript_regular',
  'AkayaKanadaka_regular',
  'AkayaTelivigala_regular',
  'Akronim_regular',
  'Akshar_regular',
  'Aladin_regular',
  'Alata_regular',
  'Alatsi_regular',
  'Aldrich_regular',
  'Alef_regular',
  'Alegreya_regular',
  'AlegreyaSC_regular',
  'AlegreyaSans_regular',
  'AlegreyaSansSC_regular',
  'Aleo_regular',
  'AlexBrush_regular',
  'AlfaSlabOne_regular',
  'Alice_regular',
  'Alike_regular',
  'AlikeAngular_regular',
  'Allan_regular',
  'Allerta_regular',
  'AllertaStencil_regular',
  'Allison_regular',
  'Allura_regular',
  'Almarai_regular',
  'Almendra_regular',
  'AlmendraDisplay_regular',
  'AlmendraSC_regular',
  'AlumniSans_regular',
  'AlumniSansInlineOne_regular',
  'Amarante_regular',
  'Amaranth_regular',
  'AmaticSC_regular',
  'Amethysta_regular',
  'Amiko_regular',
  'Amiri_regular',
  'Amita_regular',
  'Anaheim_regular',
  'AndadaPro_regular',
  'Andika_regular',
  'AndikaNewBasic_regular',
  'AnekBangla_regular',
  'AnekDevanagari_regular',
  'AnekGujarati_regular',
  'AnekGurmukhi_regular',
  'AnekKannada_regular',
  'AnekLatin_regular',
  'AnekMalayalam_regular',
  'AnekOdia_regular',
  'AnekTamil_regular',
  'AnekTelugu_regular',
  'Angkor_regular',
  'AnnieUseYourTelescope_regular',
  'AnonymousPro_regular',
  'Antic_regular',
  'AnticDidone_regular',
  'AnticSlab_regular',
  'Anton_regular',
  'Antonio_regular',
  'Anybody_regular',
  'Arapey_regular',
  'Arbutus_regular',
  'ArbutusSlab_regular',
  'ArchitectsDaughter_regular',
  'Archivo_regular',
  'ArchivoBlack_regular',
  'ArchivoNarrow_regular',
  'AreYouSerious_regular',
  'ArefRuqaa_regular',
  'ArimaMadurai_regular',
  'Arimo_regular',
  'Arizonia_regular',
  'Armata_regular',
  'Arsenal_regular',
  'Artifika_regular',
  'Arvo_regular',
  'Arya_regular',
  'Asap_regular',
  'AsapCondensed_regular',
  'Asar_regular',
  'Asset_regular',
  'Assistant_regular',
  'Astloch_regular',
  'Asul_regular',
  'Athiti_regular',
  'AtkinsonHyperlegible_regular',
  'Atma_regular',
  'AtomicAge_regular',
  'Aubrey_regular',
  'Audiowide_regular',
  'AutourOne_regular',
  'Average_regular',
  'AverageSans_regular',
  'AveriaGruesaLibre_regular',
  'AveriaLibre_regular',
  'AveriaSansLibre_regular',
  'AveriaSerifLibre_regular',
  'AzeretMono_regular',
  'B612_regular',
  'B612Mono_regular',
  'BIZUDGothic_regular',
  'BIZUDMincho_regular',
  'BIZUDPGothic_regular',
  'BIZUDPMincho_regular',
  'Babylonica_regular',
  'BadScript_regular',
  'Bahiana_regular',
  'Bahianita_regular',
  'BaiJamjuree_regular',
  'BakbakOne_regular',
  'Ballet_regular',
  'Baloo2_regular',
  'BalooBhai2_regular',
  'BalooBhaijaan2_regular',
  'BalooBhaina2_regular',
  'BalooChettan2_regular',
  'BalooDa2_regular',
  'BalooPaaji2_regular',
  'BalooTamma2_regular',
  'BalooTammudu2_regular',
  'BalooThambi2_regular',
  'BalsamiqSans_regular',
  'Balthazar_regular',
  'Bangers_regular',
  'Barlow_regular',
  'BarlowCondensed_regular',
  'BarlowSemiCondensed_regular',
  'Barriecito_regular',
  'Barrio_regular',
  'Basic_regular',
  'Baskervville_regular',
  'Battambang_regular',
  'Baumans_regular',
  'Bayon_regular',
  'BeVietnamPro_regular',
  'BeauRivage_regular',
  'BebasNeue_regular',
  'Belgrano_regular',
  'Bellefair_regular',
  'Belleza_regular',
  'Bellota_regular',
  'BellotaText_regular',
  'BenchNine_regular',
  'Benne_regular',
  'Bentham_regular',
  'BerkshireSwash_regular',
  'Besley_regular',
  'BethEllen_regular',
  'Bevan_regular',
  'BhuTukaExpandedOne_regular',
  'BigShouldersDisplay_regular',
  'BigShouldersInlineDisplay_regular',
  'BigShouldersInlineText_regular',
  'BigShouldersStencilDisplay_regular',
  'BigShouldersStencilText_regular',
  'BigShouldersText_regular',
  'BigelowRules_regular',
  'BigshotOne_regular',
  'Bilbo_regular',
  'BilboSwashCaps_regular',
  'BioRhyme_regular',
  'BioRhymeExpanded_regular',
  'Birthstone_regular',
  'BirthstoneBounce_regular',
  'Biryani_regular',
  'Bitter_regular',
  'BlackAndWhitePicture_regular',
  'BlackHanSans_regular',
  'BlackOpsOne_regular',
  'Blinker_regular',
  'BodoniModa_regular',
  'Bokor_regular',
  'BonaNova_regular',
  'Bonbon_regular',
  'BonheurRoyale_regular',
  'Boogaloo_regular',
  'BowlbyOne_regular',
  'BowlbyOneSC_regular',
  'Brawler_regular',
  'BreeSerif_regular',
  'Brygada1918_regular',
  'BubblegumSans_regular',
  'BubblerOne_regular',
  'Buda_300',
  'Buenard_regular',
  'Bungee_regular',
  'BungeeHairline_regular',
  'BungeeInline_regular',
  'BungeeOutline_regular',
  'BungeeShade_regular',
  'Butcherman_regular',
  'ButterflyKids_regular',
  'Cabin_regular',
  'CabinCondensed_regular',
  'CabinSketch_regular',
  'CaesarDressing_regular',
  'Cagliostro_regular',
  'Cairo_regular',
  'Caladea_regular',
  'Calistoga_regular',
  'Calligraffitti_regular',
  'Cambay_regular',
  'Cambo_regular',
  'Candal_regular',
  'Cantarell_regular',
  'CantataOne_regular',
  'CantoraOne_regular',
  'Capriola_regular',
  'Caramel_regular',
  'Carattere_regular',
  'Cardo_regular',
  'Carme_regular',
  'CarroisGothic_regular',
  'CarroisGothicSC_regular',
  'CarterOne_regular',
  'Castoro_regular',
  'Catamaran_regular',
  'Caudex_regular',
  'Caveat_regular',
  'CaveatBrush_regular',
  'CedarvilleCursive_regular',
  'CevicheOne_regular',
  'ChakraPetch_regular',
  'Changa_regular',
  'ChangaOne_regular',
  'Chango_regular',
  'Charm_regular',
  'Charmonman_regular',
  'Chathura_regular',
  'ChauPhilomeneOne_regular',
  'ChelaOne_regular',
  'ChelseaMarket_regular',
  'Chenla_regular',
  'Cherish_regular',
  'CherryCreamSoda_regular',
  'CherrySwash_regular',
  'Chewy_regular',
  'Chicle_regular',
  'Chilanka_regular',
  'Chivo_regular',
  'Chonburi_regular',
  'Cinzel_regular',
  'CinzelDecorative_regular',
  'ClickerScript_regular',
  'Coda_regular',
  'CodaCaption_800',
  'Codystar_regular',
  'Coiny_regular',
  'Combo_regular',
  'Comfortaa_regular',
  'Comforter_regular',
  'ComforterBrush_regular',
  'ComicNeue_regular',
  'ComingSoon_regular',
  'Commissioner_regular',
  'ConcertOne_regular',
  'Condiment_regular',
  'Content_regular',
  'ContrailOne_regular',
  'Convergence_regular',
  'Cookie_regular',
  'Copse_regular',
  'Corben_regular',
  'Corinthia_regular',
  'Cormorant_regular',
  'CormorantGaramond_regular',
  'CormorantInfant_regular',
  'CormorantSC_regular',
  'CormorantUnicase_regular',
  'CormorantUpright_regular',
  'Courgette_regular',
  'CourierPrime_regular',
  'Cousine_regular',
  'Coustard_regular',
  'CoveredByYourGrace_regular',
  'CraftyGirls_regular',
  'Creepster_regular',
  'CreteRound_regular',
  'CrimsonPro_regular',
  'CroissantOne_regular',
  'Crushed_regular',
  'Cuprum_regular',
  'CuteFont_regular',
  'Cutive_regular',
  'CutiveMono_regular',
  'DMMono_regular',
  'DMSans_regular',
  'DMSerifDisplay_regular',
  'DMSerifText_regular',
  'Damion_regular',
  'DancingScript_regular',
  'Dangrek_regular',
  'DarkerGrotesque_regular',
  'DavidLibre_regular',
  'DawningofaNewDay_regular',
  'DaysOne_regular',
  'Dekko_regular',
  'DelaGothicOne_regular',
  'Delius_regular',
  'DeliusSwashCaps_regular',
  'DeliusUnicase_regular',
  'DellaRespira_regular',
  'DenkOne_regular',
  'Devonshire_regular',
  'Dhurjati_regular',
  'DidactGothic_regular',
  'Diplomata_regular',
  'DiplomataSC_regular',
  'DoHyeon_regular',
  'Dokdo_regular',
  'Domine_regular',
  'DonegalOne_regular',
  'Dongle_regular',
  'DoppioOne_regular',
  'Dorsa_regular',
  'Dosis_regular',
  'DotGothic16_regular',
  'DrSugiyama_regular',
  'DuruSans_regular',
  'Dynalight_regular',
  'EBGaramond_regular',
  'EagleLake_regular',
  'EastSeaDokdo_regular',
  'Eater_regular',
  'Economica_regular',
  'Eczar_regular',
  'ElMessiri_regular',
  'Electrolize_regular',
  'Elsie_regular',
  'ElsieSwashCaps_regular',
  'EmblemaOne_regular',
  'EmilysCandy_regular',
  'EncodeSans_regular',
  'EncodeSansCondensed_regular',
  'EncodeSansExpanded_regular',
  'EncodeSansSC_regular',
  'EncodeSansSemiCondensed_regular',
  'EncodeSansSemiExpanded_regular',
  'Engagement_regular',
  'Englebert_regular',
  'Enriqueta_regular',
  'Ephesis_regular',
  'Epilogue_regular',
  'EricaOne_regular',
  'Esteban_regular',
  'Estonia_regular',
  'EuphoriaScript_regular',
  'Ewert_regular',
  'Exo_regular',
  'Exo2_regular',
  'ExpletusSans_regular',
  'Explora_regular',
  'Fahkwang_regular',
  'FamiljenGrotesk_regular',
  'FanwoodText_regular',
  'Farro_regular',
  'Farsan_regular',
  'Fascinate_regular',
  'FascinateInline_regular',
  'FasterOne_regular',
  'Fasthand_regular',
  'FaunaOne_regular',
  'Faustina_regular',
  'Federant_regular',
  'Federo_regular',
  'Felipa_regular',
  'Fenix_regular',
  'Festive_regular',
  'FingerPaint_regular',
  'FiraCode_regular',
  'FiraMono_regular',
  'FiraSans_regular',
  'FiraSansCondensed_regular',
  'FiraSansExtraCondensed_regular',
  'FjallaOne_regular',
  'FjordOne_regular',
  'Flamenco_regular',
  'Flavors_regular',
  'FleurDeLeah_regular',
  'FlowBlock_regular',
  'FlowCircular_regular',
  'FlowRounded_regular',
  'Fondamento_regular',
  'FontdinerSwanky_regular',
  'Forum_regular',
  'FrancoisOne_regular',
  'FrankRuhlLibre_regular',
  'Fraunces_regular',
  'FreckleFace_regular',
  'FrederickatheGreat_regular',
  'Fredoka_regular',
  'FredokaOne_regular',
  'Freehand_regular',
  'Fresca_regular',
  'Frijole_regular',
  'Fruktur_regular',
  'FugazOne_regular',
  'Fuggles_regular',
  'FuzzyBubbles_regular',
  'GFSDidot_regular',
  'GFSNeohellenic_regular',
  'Gabriela_regular',
  'Gaegu_regular',
  'Gafata_regular',
  'Galada_regular',
  'Galdeano_regular',
  'Galindo_regular',
  'GamjaFlower_regular',
  'Gayathri_regular',
  'Gelasio_regular',
  'GemunuLibre_regular',
  'Genos_regular',
  'GentiumBasic_regular',
  'GentiumBookBasic_regular',
  'Geo_regular',
  'Georama_regular',
  'Geostar_regular',
  'GeostarFill_regular',
  'GermaniaOne_regular',
  'GideonRoman_regular',
  'Gidugu_regular',
  'GildaDisplay_regular',
  'Girassol_regular',
  'GiveYouGlory_regular',
  'GlassAntiqua_regular',
  'Glegoo_regular',
  'GloriaHallelujah_regular',
  'Glory_regular',
  'Gluten_regular',
  'GoblinOne_regular',
  'GochiHand_regular',
  'Goldman_regular',
  'Gorditas_regular',
  'GothicA1_regular',
  'Gotu_regular',
  'GoudyBookletter1911_regular',
  'GowunBatang_regular',
  'GowunDodum_regular',
  'Graduate_regular',
  'GrandHotel_regular',
  'Grandstander_regular',
  'GrapeNuts_regular',
  'GravitasOne_regular',
  'GreatVibes_regular',
  'GrechenFuemen_regular',
  'Grenze_regular',
  'GrenzeGotisch_regular',
  'GreyQo_regular',
  'Griffy_regular',
  'Gruppo_regular',
  'Gudea_regular',
  'Gugi_regular',
  'Gupter_regular',
  'Gurajada_regular',
  'Gwendolyn_regular',
  'Habibi_regular',
  'HachiMaruPop_regular',
  'Hahmlet_regular',
  'Halant_regular',
  'HammersmithOne_regular',
  'Hanalei_regular',
  'HanaleiFill_regular',
  'Handlee_regular',
  'Hanuman_regular',
  'HappyMonkey_regular',
  'Harmattan_regular',
  'HeadlandOne_regular',
  'Heebo_regular',
  'HennyPenny_regular',
  'HeptaSlab_regular',
  'HerrVonMuellerhoff_regular',
  'HiMelody_regular',
  'HinaMincho_regular',
  'Hind_regular',
  'HindGuntur_regular',
  'HindMadurai_regular',
  'HindSiliguri_regular',
  'HindVadodara_regular',
  'HoltwoodOneSC_regular',
  'HomemadeApple_regular',
  'Homenaje_regular',
  'Hubballi_regular',
  'Hurricane_regular',
  'IBMPlexMono_regular',
  'IBMPlexSans_regular',
  'IBMPlexSansArabic_regular',
  'IBMPlexSansCondensed_regular',
  'IBMPlexSansDevanagari_regular',
  'IBMPlexSansHebrew_regular',
  'IBMPlexSansKR_regular',
  'IBMPlexSansThai_regular',
  'IBMPlexSansThaiLooped_regular',
  'IBMPlexSerif_regular',
  'IMFellDWPica_regular',
  'IMFellDWPicaSC_regular',
  'IMFellDoublePica_regular',
  'IMFellDoublePicaSC_regular',
  'IMFellEnglish_regular',
  'IMFellEnglishSC_regular',
  'IMFellFrenchCanon_regular',
  'IMFellFrenchCanonSC_regular',
  'IMFellGreatPrimer_regular',
  'IMFellGreatPrimerSC_regular',
  'IbarraRealNova_regular',
  'Iceberg_regular',
  'Iceland_regular',
  'Imbue_regular',
  'ImperialScript_regular',
  'Imprima_regular',
  'Inconsolata_regular',
  'Inder_regular',
  'IndieFlower_regular',
  'IngridDarling_regular',
  'Inika_regular',
  'InknutAntiqua_regular',
  'InriaSans_regular',
  'InriaSerif_regular',
  'Inspiration_regular',
  'Inter_regular',
  'IrishGrover_regular',
  'IslandMoments_regular',
  'IstokWeb_regular',
  'Italiana_regular',
  'Italianno_regular',
  'Itim_regular',
  'JacquesFrancois_regular',
  'JacquesFrancoisShadow_regular',
  'Jaldi_regular',
  'JetBrainsMono_regular',
  'JimNightshade_regular',
  'JockeyOne_regular',
  'JollyLodger_regular',
  'Jomhuria_regular',
  'Jomolhari_regular',
  'JosefinSans_regular',
  'JosefinSlab_regular',
  'Jost_regular',
  'JotiOne_regular',
  'Jua_regular',
  'Judson_regular',
  'Julee_regular',
  'JuliusSansOne_regular',
  'Junge_regular',
  'Jura_regular',
  'JustAnotherHand_regular',
  'JustMeAgainDownHere_regular',
  'K2D_regular',
  'Kadwa_regular',
  'KaiseiDecol_regular',
  'KaiseiHarunoUmi_regular',
  'KaiseiOpti_regular',
  'KaiseiTokumin_regular',
  'Kalam_regular',
  'Kameron_regular',
  'Kanit_regular',
  'Kantumruy_regular',
  'Karantina_regular',
  'Karla_regular',
  'Karma_regular',
  'Katibeh_regular',
  'KaushanScript_regular',
  'Kavivanar_regular',
  'Kavoon_regular',
  'KdamThmor_regular',
  'KeaniaOne_regular',
  'KellySlab_regular',
  'Kenia_regular',
  'Khand_regular',
  'Khmer_regular',
  'Khula_regular',
  'Kings_regular',
  'KirangHaerang_regular',
  'KiteOne_regular',
  'KiwiMaru_regular',
  'KleeOne_regular',
  'Knewave_regular',
  'KoHo_regular',
  'Kodchasan_regular',
  'KohSantepheap_regular',
  'KolkerBrush_regular',
  'Kosugi_regular',
  'KosugiMaru_regular',
  'KottaOne_regular',
  'Koulen_regular',
  'Kranky_regular',
  'Kreon_regular',
  'Kristi_regular',
  'KronaOne_regular',
  'Krub_regular',
  'Kufam_regular',
  'KulimPark_regular',
  'KumarOne_regular',
  'KumarOneOutline_regular',
  'KumbhSans_regular',
  'Kurale_regular',
  'LaBelleAurore_regular',
  'Lacquer_regular',
  'Laila_regular',
  'LakkiReddy_regular',
  'Lalezar_regular',
  'Lancelot_regular',
  'Langar_regular',
  'Lateef_regular',
  'Lato_regular',
  'LavishlyYours_regular',
  'LeagueGothic_regular',
  'LeagueScript_regular',
  'LeagueSpartan_regular',
  'LeckerliOne_regular',
  'Ledger_regular',
  'Lekton_regular',
  'Lemon_regular',
  'Lemonada_regular',
  'Lexend_regular',
  'LexendDeca_regular',
  'LexendExa_regular',
  'LexendGiga_regular',
  'LexendMega_regular',
  'LexendPeta_regular',
  'LexendTera_regular',
  'LexendZetta_regular',
  'LibreBarcode128_regular',
  'LibreBarcode128Text_regular',
  'LibreBarcode39_regular',
  'LibreBarcode39Extended_regular',
  'LibreBarcode39ExtendedText_regular',
  'LibreBarcode39Text_regular',
  'LibreBarcodeEAN13Text_regular',
  'LibreBaskerville_regular',
  'LibreBodoni_regular',
  'LibreCaslonDisplay_regular',
  'LibreCaslonText_regular',
  'LibreFranklin_regular',
  'Licorice_regular',
  'LifeSavers_regular',
  'LilitaOne_regular',
  'LilyScriptOne_regular',
  'Limelight_regular',
  'LindenHill_regular',
  'Literata_regular',
  'LiuJianMaoCao_regular',
  'Livvic_regular',
  'Lobster_regular',
  'LobsterTwo_regular',
  'LondrinaOutline_regular',
  'LondrinaShadow_regular',
  'LondrinaSketch_regular',
  'LondrinaSolid_regular',
  'LongCang_regular',
  'Lora_regular',
  'LoveLight_regular',
  'LoveYaLikeASister_regular',
  'LovedbytheKing_regular',
  'LoversQuarrel_regular',
  'LuckiestGuy_regular',
  'Lusitana_regular',
  'Lustria_regular',
  'LuxuriousRoman_regular',
  'LuxuriousScript_regular',
  'MPLUS1_regular',
  'MPLUS1Code_regular',
  'MPLUS1p_regular',
  'MPLUS2_regular',
  'MPLUSCodeLatin_regular',
  'MPLUSRounded1c_regular',
  'MaShanZheng_regular',
  'Macondo_regular',
  'MacondoSwashCaps_regular',
  'Mada_regular',
  'Magra_regular',
  'MaidenOrange_regular',
  'Maitree_regular',
  'MajorMonoDisplay_regular',
  'Mako_regular',
  'Mali_regular',
  'Mallanna_regular',
  'Mandali_regular',
  'Manjari_regular',
  'Manrope_regular',
  'Mansalva_regular',
  'Manuale_regular',
  'Marcellus_regular',
  'MarcellusSC_regular',
  'MarckScript_regular',
  'Margarine_regular',
  'MarkaziText_regular',
  'MarkoOne_regular',
  'Marmelad_regular',
  'Martel_regular',
  'MartelSans_regular',
  'Marvel_regular',
  'Mate_regular',
  'MateSC_regular',
  'MavenPro_regular',
  'McLaren_regular',
  'MeaCulpa_regular',
  'Meddon_regular',
  'MedievalSharp_regular',
  'MedulaOne_regular',
  'MeeraInimai_regular',
  'Megrim_regular',
  'MeieScript_regular',
  'MeowScript_regular',
  'Merienda_regular',
  'MeriendaOne_regular',
  'Merriweather_regular',
  'MerriweatherSans_regular',
  'Metal_regular',
  'MetalMania_regular',
  'Metamorphous_regular',
  'Metrophobic_regular',
  'Michroma_regular',
  'Milonga_regular',
  'Miltonian_regular',
  'MiltonianTattoo_regular',
  'Mina_regular',
  'Miniver_regular',
  'MiriamLibre_regular',
  'Mirza_regular',
  'MissFajardose_regular',
  'Mitr_regular',
  'MochiyPopOne_regular',
  'MochiyPopPOne_regular',
  'Modak_regular',
  'ModernAntiqua_regular',
  'Mogra_regular',
  'Mohave_regular',
  'Molengo_regular',
  'Molle_italic',
  'Monda_regular',
  'Monofett_regular',
  'Monoton_regular',
  'MonsieurLaDoulaise_regular',
  'Montaga_regular',
  'MontaguSlab_regular',
  'MonteCarlo_regular',
  'Montez_regular',
  'Montserrat_regular',
  'MontserratAlternates_regular',
  'MontserratSubrayada_regular',
  'MooLahLah_regular',
  'MoonDance_regular',
  'Moul_regular',
  'Moulpali_regular',
  'MountainsofChristmas_regular',
  'MouseMemoirs_regular',
  'MrBedfort_regular',
  'MrDafoe_regular',
  'MrDeHaviland_regular',
  'MrsSaintDelafield_regular',
  'MrsSheppards_regular',
  'MsMadi_regular',
  'Mukta_regular',
  'MuktaMahee_regular',
  'MuktaMalar_regular',
  'MuktaVaani_regular',
  'Mulish_regular',
  'Murecho_regular',
  'MuseoModerno_regular',
  'MySoul_regular',
  'MysteryQuest_regular',
  'NTR_regular',
  'NanumBrushScript_regular',
  'NanumGothic_regular',
  'NanumGothicCoding_regular',
  'NanumMyeongjo_regular',
  'NanumPenScript_regular',
  'Neonderthaw_regular',
  'NerkoOne_regular',
  'Neucha_regular',
  'Neuton_regular',
  'NewRocker_regular',
  'NewTegomin_regular',
  'NewsCycle_regular',
  'Newsreader_regular',
  'Niconne_regular',
  'Niramit_regular',
  'NixieOne_regular',
  'Nobile_regular',
  'Nokora_regular',
  'Norican_regular',
  'Nosifer_regular',
  'Notable_regular',
  'NothingYouCouldDo_regular',
  'NoticiaText_regular',
  'NotoEmoji_regular',
  'NotoKufiArabic_regular',
  'NotoMusic_regular',
  'NotoNaskhArabic_regular',
  'NotoNastaliqUrdu_regular',
  'NotoRashiHebrew_regular',
  'NotoSans_regular',
  'NotoSansAdlam_regular',
  'NotoSansAdlamUnjoined_regular',
  'NotoSansAnatolianHieroglyphs_regular',
  'NotoSansArabic_regular',
  'NotoSansArmenian_regular',
  'NotoSansAvestan_regular',
  'NotoSansBalinese_regular',
  'NotoSansBamum_regular',
  'NotoSansBassaVah_regular',
  'NotoSansBatak_regular',
  'NotoSansBengali_regular',
  'NotoSansBhaiksuki_regular',
  'NotoSansBrahmi_regular',
  'NotoSansBuginese_regular',
  'NotoSansBuhid_regular',
  'NotoSansCanadianAboriginal_regular',
  'NotoSansCarian_regular',
  'NotoSansCaucasianAlbanian_regular',
  'NotoSansChakma_regular',
  'NotoSansCham_regular',
  'NotoSansCherokee_regular',
  'NotoSansCoptic_regular',
  'NotoSansCuneiform_regular',
  'NotoSansCypriot_regular',
  'NotoSansDeseret_regular',
  'NotoSansDevanagari_regular',
  'NotoSansDisplay_regular',
  'NotoSansDuployan_regular',
  'NotoSansEgyptianHieroglyphs_regular',
  'NotoSansElbasan_regular',
  'NotoSansElymaic_regular',
  'NotoSansGeorgian_regular',
  'NotoSansGlagolitic_regular',
  'NotoSansGothic_regular',
  'NotoSansGrantha_regular',
  'NotoSansGujarati_regular',
  'NotoSansGunjalaGondi_regular',
  'NotoSansGurmukhi_regular',
  'NotoSansHanifiRohingya_regular',
  'NotoSansHanunoo_regular',
  'NotoSansHatran_regular',
  'NotoSansHebrew_regular',
  'NotoSansImperialAramaic_regular',
  'NotoSansIndicSiyaqNumbers_regular',
  'NotoSansInscriptionalPahlavi_regular',
  'NotoSansInscriptionalParthian_regular',
  'NotoSansJavanese_regular',
  'NotoSansKaithi_regular',
  'NotoSansKannada_regular',
  'NotoSansKayahLi_regular',
  'NotoSansKharoshthi_regular',
  'NotoSansKhmer_regular',
  'NotoSansKhojki_regular',
  'NotoSansKhudawadi_regular',
  'NotoSansLao_regular',
  'NotoSansLepcha_regular',
  'NotoSansLimbu_regular',
  'NotoSansLinearA_regular',
  'NotoSansLinearB_regular',
  'NotoSansLisu_regular',
  'NotoSansLycian_regular',
  'NotoSansLydian_regular',
  'NotoSansMahajani_regular',
  'NotoSansMalayalam_regular',
  'NotoSansMandaic_regular',
  'NotoSansManichaean_regular',
  'NotoSansMarchen_regular',
  'NotoSansMasaramGondi_regular',
  'NotoSansMath_regular',
  'NotoSansMayanNumerals_regular',
  'NotoSansMedefaidrin_regular',
  'NotoSansMeeteiMayek_regular',
  'NotoSansMeroitic_regular',
  'NotoSansMiao_regular',
  'NotoSansModi_regular',
  'NotoSansMongolian_regular',
  'NotoSansMono_regular',
  'NotoSansMro_regular',
  'NotoSansMultani_regular',
  'NotoSansMyanmar_regular',
  'NotoSansNKo_regular',
  'NotoSansNabataean_regular',
  'NotoSansNewTaiLue_regular',
  'NotoSansNewa_regular',
  'NotoSansNushu_regular',
  'NotoSansOgham_regular',
  'NotoSansOlChiki_regular',
  'NotoSansOldHungarian_regular',
  'NotoSansOldItalic_regular',
  'NotoSansOldNorthArabian_regular',
  'NotoSansOldPermic_regular',
  'NotoSansOldPersian_regular',
  'NotoSansOldSogdian_regular',
  'NotoSansOldSouthArabian_regular',
  'NotoSansOldTurkic_regular',
  'NotoSansOriya_regular',
  'NotoSansOsage_regular',
  'NotoSansOsmanya_regular',
  'NotoSansPahawhHmong_regular',
  'NotoSansPalmyrene_regular',
  'NotoSansPauCinHau_regular',
  'NotoSansPhagsPa_regular',
  'NotoSansPhoenician_regular',
  'NotoSansPsalterPahlavi_regular',
  'NotoSansRejang_regular',
  'NotoSansRunic_regular',
  'NotoSansSamaritan_regular',
  'NotoSansSaurashtra_regular',
  'NotoSansSharada_regular',
  'NotoSansShavian_regular',
  'NotoSansSiddham_regular',
  'NotoSansSinhala_regular',
  'NotoSansSogdian_regular',
  'NotoSansSoraSompeng_regular',
  'NotoSansSoyombo_regular',
  'NotoSansSundanese_regular',
  'NotoSansSylotiNagri_regular',
  'NotoSansSymbols_regular',
  'NotoSansSymbols2_regular',
  'NotoSansSyriac_regular',
  'NotoSansTagalog_regular',
  'NotoSansTagbanwa_regular',
  'NotoSansTaiLe_regular',
  'NotoSansTaiTham_regular',
  'NotoSansTaiViet_regular',
  'NotoSansTakri_regular',
  'NotoSansTamil_regular',
  'NotoSansTamilSupplement_regular',
  'NotoSansTelugu_regular',
  'NotoSansThaana_regular',
  'NotoSansThai_regular',
  'NotoSansThaiLooped_regular',
  'NotoSansTifinagh_regular',
  'NotoSansTirhuta_regular',
  'NotoSansUgaritic_regular',
  'NotoSansVai_regular',
  'NotoSansWancho_regular',
  'NotoSansWarangCiti_regular',
  'NotoSansYi_regular',
  'NotoSansZanabazarSquare_regular',
  'NotoSerif_regular',
  'NotoSerifAhom_regular',
  'NotoSerifArmenian_regular',
  'NotoSerifBalinese_regular',
  'NotoSerifBengali_regular',
  'NotoSerifDevanagari_regular',
  'NotoSerifDisplay_regular',
  'NotoSerifDogra_regular',
  'NotoSerifEthiopic_regular',
  'NotoSerifGeorgian_regular',
  'NotoSerifGrantha_regular',
  'NotoSerifGujarati_regular',
  'NotoSerifGurmukhi_regular',
  'NotoSerifHebrew_regular',
  'NotoSerifKannada_regular',
  'NotoSerifKhmer_regular',
  'NotoSerifLao_regular',
  'NotoSerifMalayalam_regular',
  'NotoSerifMyanmar_regular',
  'NotoSerifNyiakengPuachueHmong_regular',
  'NotoSerifSinhala_regular',
  'NotoSerifTamil_regular',
  'NotoSerifTangut_regular',
  'NotoSerifTelugu_regular',
  'NotoSerifThai_regular',
  'NotoSerifTibetan_regular',
  'NotoSerifYezidi_regular',
  'NotoTraditionalNushu_regular',
  'NovaCut_regular',
  'NovaFlat_regular',
  'NovaMono_regular',
  'NovaOval_regular',
  'NovaRound_regular',
  'NovaScript_regular',
  'NovaSlim_regular',
  'NovaSquare_regular',
  'Numans_regular',
  'Nunito_regular',
  'NunitoSans_regular',
  'OdibeeSans_regular',
  'OdorMeanChey_regular',
  'Offside_regular',
  'Oi_regular',
  'OldStandardTT_regular',
  'Oldenburg_regular',
  'Ole_regular',
  'OleoScript_regular',
  'OleoScriptSwashCaps_regular',
  'OoohBaby_regular',
  'OpenSans_regular',
  'OpenSansCondensed_300',
  'Oranienbaum_regular',
  'Orbitron_regular',
  'Oregano_regular',
  'OrelegaOne_regular',
  'Orienta_regular',
  'OriginalSurfer_regular',
  'Oswald_regular',
  'OtomanopeeOne_regular',
  'Outfit_regular',
  'OvertheRainbow_regular',
  'Overlock_regular',
  'OverlockSC_regular',
  'Overpass_regular',
  'OverpassMono_regular',
  'Ovo_regular',
  'Oxanium_regular',
  'Oxygen_regular',
  'OxygenMono_regular',
  'PTMono_regular',
  'PTSans_regular',
  'PTSansCaption_regular',
  'PTSansNarrow_regular',
  'PTSerif_regular',
  'PTSerifCaption_regular',
  'Pacifico_regular',
  'Padauk_regular',
  'Palanquin_regular',
  'PalanquinDark_regular',
  'PaletteMosaic_regular',
  'Pangolin_regular',
  'Paprika_regular',
  'Parisienne_regular',
  'PasseroOne_regular',
  'PassionOne_regular',
  'PassionsConflict_regular',
  'PathwayGothicOne_regular',
  'PatrickHand_regular',
  'PatrickHandSC_regular',
  'Pattaya_regular',
  'PatuaOne_regular',
  'Pavanam_regular',
  'PaytoneOne_regular',
  'Peddana_regular',
  'Peralta_regular',
  'PermanentMarker_regular',
  'Petemoss_regular',
  'PetitFormalScript_regular',
  'Petrona_regular',
  'Philosopher_regular',
  'Piazzolla_regular',
  'Piedra_regular',
  'PinyonScript_regular',
  'PirataOne_regular',
  'Plaster_regular',
  'Play_regular',
  'Playball_regular',
  'PlayfairDisplay_regular',
  'PlayfairDisplaySC_regular',
  'PlusJakartaSans_regular',
  'Podkova_regular',
  'PoiretOne_regular',
  'PollerOne_regular',
  'Poly_regular',
  'Pompiere_regular',
  'PontanoSans_regular',
  'PoorStory_regular',
  'Poppins_regular',
  'PortLligatSans_regular',
  'PortLligatSlab_regular',
  'PottaOne_regular',
  'PragatiNarrow_regular',
  'Praise_regular',
  'Prata_regular',
  'Preahvihear_regular',
  'PressStart2P_regular',
  'Pridi_regular',
  'PrincessSofia_regular',
  'Prociono_regular',
  'Prompt_regular',
  'ProstoOne_regular',
  'ProzaLibre_regular',
  'PublicSans_regular',
  'PuppiesPlay_regular',
  'Puritan_regular',
  'PurplePurse_regular',
  'Qahiri_regular',
  'Quando_regular',
  'Quantico_regular',
  'Quattrocento_regular',
  'QuattrocentoSans_regular',
  'Questrial_regular',
  'Quicksand_regular',
  'Quintessential_regular',
  'Qwigley_regular',
  'QwitcherGrypen_regular',
  'RacingSansOne_regular',
  'RadioCanada_regular',
  'Radley_regular',
  'Rajdhani_regular',
  'Rakkas_regular',
  'Raleway_regular',
  'RalewayDots_regular',
  'Ramabhadra_regular',
  'Ramaraja_regular',
  'Rambla_regular',
  'RammettoOne_regular',
  'RampartOne_regular',
  'Ranchers_regular',
  'Rancho_regular',
  'Ranga_regular',
  'Rasa_regular',
  'Rationale_regular',
  'RaviPrakash_regular',
  'ReadexPro_regular',
  'Recursive_regular',
  'RedHatDisplay_regular',
  'RedHatMono_regular',
  'RedHatText_regular',
  'RedRose_regular',
  'Redacted_regular',
  'RedactedScript_regular',
  'Redressed_regular',
  'ReemKufi_regular',
  'ReenieBeanie_regular',
  'ReggaeOne_regular',
  'Revalia_regular',
  'RhodiumLibre_regular',
  'Ribeye_regular',
  'RibeyeMarrow_regular',
  'Righteous_regular',
  'Risque_regular',
  'RoadRage_regular',
  'Roboto_regular',
  'RobotoCondensed_regular',
  'RobotoFlex_regular',
  'RobotoMono_regular',
  'RobotoSerif_regular',
  'RobotoSlab_regular',
  'Rochester_regular',
  'Rock3D_regular',
  'RockSalt_regular',
  'RocknRollOne_regular',
  'Rokkitt_regular',
  'Romanesco_regular',
  'RopaSans_regular',
  'Rosario_regular',
  'Rosarivo_regular',
  'RougeScript_regular',
  'Rowdies_regular',
  'RozhaOne_regular',
  'Rubik_regular',
  'RubikBeastly_regular',
  'RubikBubbles_regular',
  'RubikGlitch_regular',
  'RubikMicrobe_regular',
  'RubikMonoOne_regular',
  'RubikMoonrocks_regular',
  'RubikPuddles_regular',
  'RubikWetPaint_regular',
  'Ruda_regular',
  'Rufina_regular',
  'RugeBoogie_regular',
  'Ruluko_regular',
  'RumRaisin_regular',
  'RuslanDisplay_regular',
  'RussoOne_regular',
  'Ruthie_regular',
  'Rye_regular',
  'STIXTwoText_regular',
  'Sacramento_regular',
  'Sahitya_regular',
  'Sail_regular',
  'Saira_regular',
  'SairaCondensed_regular',
  'SairaExtraCondensed_regular',
  'SairaSemiCondensed_regular',
  'SairaStencilOne_regular',
  'Salsa_regular',
  'Sanchez_regular',
  'Sancreek_regular',
  'Sansita_regular',
  'SansitaSwashed_regular',
  'Sarabun_regular',
  'Sarala_regular',
  'Sarina_regular',
  'Sarpanch_regular',
  'SassyFrass_regular',
  'Satisfy_regular',
  'SawarabiGothic_regular',
  'SawarabiMincho_regular',
  'Scada_regular',
  'ScheherazadeNew_regular',
  'Schoolbell_regular',
  'ScopeOne_regular',
  'SeaweedScript_regular',
  'SecularOne_regular',
  'SedgwickAve_regular',
  'SedgwickAveDisplay_regular',
  'Sen_regular',
  'SendFlowers_regular',
  'Sevillana_regular',
  'SeymourOne_regular',
  'ShadowsIntoLight_regular',
  'ShadowsIntoLightTwo_regular',
  'Shalimar_regular',
  'Shanti_regular',
  'Share_regular',
  'ShareTech_regular',
  'ShareTechMono_regular',
  'ShipporiAntique_regular',
  'ShipporiAntiqueB1_regular',
  'ShipporiMincho_regular',
  'ShipporiMinchoB1_regular',
  'Shizuru_regular',
  'Shojumaru_regular',
  'ShortStack_regular',
  'Shrikhand_regular',
  'Siemreap_regular',
  'SigmarOne_regular',
  'Signika_regular',
  'SignikaNegative_regular',
  'Simonetta_regular',
  'SingleDay_regular',
  'Sintony_regular',
  'SirinStencil_regular',
  'SixCaps_regular',
  'Skranji_regular',
  'Slabo13px_regular',
  'Slabo27px_regular',
  'Slackey_regular',
  'Smokum_regular',
  'Smooch_regular',
  'SmoochSans_regular',
  'Smythe_regular',
  'Sniglet_regular',
  'Snippet_regular',
  'SnowburstOne_regular',
  'SofadiOne_regular',
  'Sofia_regular',
  'Solway_regular',
  'SongMyung_regular',
  'SonsieOne_regular',
  'Sora_regular',
  'SortsMillGoudy_regular',
  'SourceCodePro_regular',
  'SourceSans3_regular',
  'SourceSansPro_regular',
  'SourceSerif4_regular',
  'SourceSerifPro_regular',
  'SpaceGrotesk_regular',
  'SpaceMono_regular',
  'SpecialElite_regular',
  'Spectral_regular',
  'SpectralSC_regular',
  'SpicyRice_regular',
  'Spinnaker_regular',
  'Spirax_regular',
  'SplineSans_regular',
  'SquadaOne_regular',
  'SquarePeg_regular',
  'SreeKrushnadevaraya_regular',
  'Sriracha_regular',
  'Srisakdi_regular',
  'Staatliches_regular',
  'Stalemate_regular',
  'StalinistOne_regular',
  'StardosStencil_regular',
  'Stick_regular',
  'StickNoBills_regular',
  'StintUltraCondensed_regular',
  'StintUltraExpanded_regular',
  'Stoke_regular',
  'Strait_regular',
  'StyleScript_regular',
  'Stylish_regular',
  'SueEllenFrancisco_regular',
  'SuezOne_regular',
  'SulphurPoint_regular',
  'Sumana_regular',
  'Sunflower_300',
  'Sunshiney_regular',
  'SupermercadoOne_regular',
  'Sura_regular',
  'Suranna_regular',
  'Suravaram_regular',
  'Suwannaphum_regular',
  'SwankyandMooMoo_regular',
  'Syncopate_regular',
  'Syne_regular',
  'SyneMono_regular',
  'SyneTactile_regular',
  'Tajawal_regular',
  'Tangerine_regular',
  'Tapestry_regular',
  'Taprom_regular',
  'Tauri_regular',
  'Taviraj_regular',
  'Teko_regular',
  'Telex_regular',
  'TenaliRamakrishna_regular',
  'TenorSans_regular',
  'TextMeOne_regular',
  'Texturina_regular',
  'Thasadith_regular',
  'TheGirlNextDoor_regular',
  'TheNautigal_regular',
  'Tienne_regular',
  'Tillana_regular',
  'Timmana_regular',
  'Tinos_regular',
  'TitanOne_regular',
  'TitilliumWeb_regular',
  'Tomorrow_regular',
  'Tourney_regular',
  'TradeWinds_regular',
  'TrainOne_regular',
  'Trirong_regular',
  'Trispace_regular',
  'Trocchi_regular',
  'Trochut_regular',
  'Truculenta_regular',
  'Trykker_regular',
  'TulpenOne_regular',
  'TurretRoad_regular',
  'TwinkleStar_regular',
  'Ubuntu_regular',
  'UbuntuCondensed_regular',
  'UbuntuMono_regular',
  'Uchen_regular',
  'Ultra_regular',
  'UncialAntiqua_regular',
  'Underdog_regular',
  'UnicaOne_regular',
  'UnifrakturCook_700',
  'UnifrakturMaguntia_regular',
  'Unkempt_regular',
  'Unlock_regular',
  'Unna_regular',
  'Updock_regular',
  'Urbanist_regular',
  'VT323_regular',
  'VampiroOne_regular',
  'Varela_regular',
  'VarelaRound_regular',
  'Varta_regular',
  'VastShadow_regular',
  'Vazirmatn_regular',
  'VesperLibre_regular',
  'ViaodaLibre_regular',
  'Vibes_regular',
  'Vibur_regular',
  'Vidaloka_regular',
  'Viga_regular',
  'Voces_regular',
  'Volkhov_regular',
  'Vollkorn_regular',
  'VollkornSC_regular',
  'Voltaire_regular',
  'VujahdayScript_regular',
  'WaitingfortheSunrise_regular',
  'Wallpoet_regular',
  'WalterTurncoat_regular',
  'Warnes_regular',
  'WaterBrush_regular',
  'Waterfall_regular',
  'Wellfleet_regular',
  'WendyOne_regular',
  'Whisper_regular',
  'WindSong_regular',
  'WireOne_regular',
  'WorkSans_regular',
  'XanhMono_regular',
  'Yaldevi_regular',
  'YanoneKaffeesatz_regular',
  'Yantramanav_regular',
  'YatraOne_regular',
  'Yellowtail_regular',
  'YeonSung_regular',
  'YesevaOne_regular',
  'Yesteryear_regular',
  'Yomogi_regular',
  'Yrsa_regular',
  'YujiBoku_regular',
  'YujiHentaiganaAkari_regular',
  'YujiHentaiganaAkebono_regular',
  'YujiMai_regular',
  'YujiSyuku_regular',
  'YuseiMagic_regular',
  'ZCOOLKuaiLe_regular',
  'ZCOOLQingKeHuangYou_regular',
  'ZCOOLXiaoWei_regular',
  'ZenAntique_regular',
  'ZenAntiqueSoft_regular',
  'ZenDots_regular',
  'ZenKakuGothicAntique_regular',
  'ZenKakuGothicNew_regular',
  'ZenKurenaido_regular',
  'ZenLoop_regular',
  'ZenMaruGothic_regular',
  'ZenOldMincho_regular',
  'ZenTokyoZoo_regular',
  'Zeyada_regular',
  'ZhiMangXing_regular',
  'ZillaSlab_regular',
  'ZillaSlabHighlight_regular',
];
