name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch: # Allows manual triggering of the workflow
jobs:
  flutter_test_and_analyze:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "18.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
  flutter_build_linux:
    name: Build flutter app for linux
    needs: [flutter_test_and_analyze]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "18.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: |
         sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build linux --release
  flutter_build_windows:
    name: Build flutter app for windows
    needs: [ flutter_test_and_analyze ]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "18.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter config --enable-windows-desktop
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build windows --release
