name: Release
on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
#  flutter_test_and_analyze:
#    name: Run flutter test and analyze
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: "18.x"
#      - uses: subosito/flutter-action@v2
#        with:
#          channel: stable
#      - run: flutter pub get
#      - run: flutter analyze
#      - run: flutter test
  flutter_build_and_release_linux:
    name: Build and release flutter app for linux
#    needs: [flutter_test_and_analyze]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "18.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: |
          sudo apt-get update -y
           sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build linux --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: Batch-Image-Editor-${{github.ref_name}}-linux.zip
          directory: build/linux/x64/release/bundle
      - name: Linux Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.BATCH_IMAGE_EDITOR_GITHUB_TOKEN }}
        with:
          files: build/linux/x64/release/bundle/Batch-Image-Editor-${{github.ref_name}}-linux.zip

  flutter_build__and_release_windows:
    name: Build and release flutter app for windows
#    needs: [ flutter_test_and_analyze ]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "18.x"
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter config --enable-windows-desktop
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build windows --release
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: Batch-Image-Editor-${{github.ref_name}}-windows.zip
          directory: build/windows/runner/Release
      - name: Windows Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.BATCH_IMAGE_EDITOR_GITHUB_TOKEN }}
        with:
          files: build/windows/runner/Release/Batch-Image-Editor-${{github.ref_name}}-windows.zip